import streamlit as st
from openai import OpenAI
import markdown
from weasyprint import HTML
import io

# Page setup
st.set_page_config(page_title="AI Construction Quotation", layout="centered")
st.title("🏗️ AI Construction Quotation Generator")

st.sidebar.header("🔑 Settings")
# API Key Secret se lega (jo hum Streamlit Cloud mein daalenge)
api_key = st.secrets.get("DEEPSEEK_API_KEY")
if not api_key:
    st.sidebar.warning("API Key missing in Secrets. Please add it.")
else:
    st.sidebar.success("API Key Loaded Successfully!")

st.sidebar.markdown("---")
st.sidebar.markdown("*📦 Package Data Format (Example):*")
st.sidebar.code("""
Foundation: 550
Structure: 1200
Finishing: 750
Electrical: 250
Plumbing: 180
Labour: 350
""")

# Main Form
st.header("📋 Client Requirements")
col1, col2 = st.columns(2)
with col1:
    client_name = st.text_input("Client Name")
    site_location = st.text_input("Site Location")
with col2:
    plot_size = st.number_input("Plot Size (sq ft)", min_value=0.0, step=100.0)
    floors = st.number_input("Floors", min_value=1, step=1)

specific_req = st.text_area("Specific Requirements (e.g., Premium Tiles)")
package_data = st.text_area("📦 Paste Your Construction Package Rates here", height=150)

# Session state
if 'quotation' not in st.session_state:
    st.session_state.quotation = None
if 'quotation_html' not in st.session_state:
    st.session_state.quotation_html = None

if st.button("🚀 Generate New Quotation", type="primary"):
    if not api_key:
        st.error("❌ API Key missing in Streamlit Secrets!")
    elif not package_data:
        st.error("❌ Kripya Package Rates paste karein.")
    else:
        with st.spinner("DeepSeek AI calculate kar raha hai..."):
            try:
                client = OpenAI(api_key=api_key, base_url="https://api.deepseek.com/v1")
                total_area = plot_size * floors
                
                prompt = f"""
                You are a professional construction cost estimator.
                RATE CARD:
                {package_data}
                CLIENT DETAILS:
                - Name: {client_name}
                - Location: {site_location}
                - Total Built-up Area: {total_area} sq ft
                - Special Requirements: {specific_req if specific_req else 'None'}
                TASK:
                1. Calculate total cost. Show breakdown per category (Foundation, Structure, etc.) in a table.
                2. If special requirements exist, add a 10-20% premium.
                3. Output in professional Markdown format with Grand Total, Validity, and T&C.
                """
                
                response = client.chat.completions.create(
                    model="deepseek-chat",
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3
                )
                
                raw = response.choices[0].message.content
                html_body = markdown.markdown(raw)
                styled = f"""
                <html><head><meta charset="UTF-8">
                <style>body{{font-family:Arial;padding:30px;}} table{{border-collapse:collapse;width:100%;}} th,td{{border:1px solid #ddd;padding:8px;text-align:left;}} th{{background:#f2f2f2;}} .total{{color:#e74c3c;font-weight:bold;}}</style>
                </head><body><h2>🏗️ CONSTRUCTION QUOTATION</h2>{html_body}<p style='margin-top:30px;font-size:12px;color:gray;'>Generated by DeepSeek AI</p></body></html>
                """
                st.session_state.quotation = raw
                st.session_state.quotation_html = styled
                st.success("✅ Quotation Generate Ho Gaya!")
            except Exception as e:
                st.error(f"⚠️ Error: {e}")

if st.session_state.quotation:
    st.markdown("---")
    st.markdown(st.session_state.quotation)
    
    if st.button("📥 Download Quotation as PDF"):
        try:
            pdf_file = HTML(string=st.session_state.quotation_html).write_pdf()
            st.download_button("✅ Click to Save PDF", data=pdf_file, file_name=f"Quotation_{client_name}.pdf", mime="application/pdf")
        except Exception as e:
            st.error(f"⚠️ PDF Error: {e}. Try using browser's 'Save as PDF' option.")